config/routes.rb
Rails.application.routes.draw do

  resources :notices
  resources :documentos
  resources :feedbacktologs
  get 'acompanhamento_gerente/index'
  resources :feedbacks
  resources :posts
  resources :logs
  resources :itematendimentoclientes
  get 'ranking/index'
  resources :itematendimentos
  resources :atendimentos do
    resources :itematendimentos
    resources :clientes
  end
  resources :itemsolics
  resources :solicitacoes do
    resources :itemsolics
  end
  resources :movfins
  resources :saidas
  resources :entradas
  get 'relacaocontratos/index'
  resources :statusprotocolos do
    resources :saidas
  end
  resources :perms
  resources :dados
  devise_for :users, :path_prefix => 'login'
  resources :users do
      resources :perms
      resources :dados
  end
  resources :permissoes
  resources :protocolos do
    resources :feedbacks
    resources :statusprotocolos
  end
  resources :bancos
  resources :clientes do
    resources :documentos
    resources :feedbacks
    resources :itematendimentoclientes
    resources :entradas
    resources :protocolos do
      resources :feedbacks
      resources :statusprotocolos do
        resources :saidas
      end
    end
  end
  root 'paginainicial#index'
  get 'paginainicial/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  
  has_many :protocolos
  has_many :itematendimentoclientes
  has_many :entradas
  has_many :feedbacks
  belongs_to :atendimento, optional: true
  has_many :documentos
  validates  :nome , :presence => {:message => ": é obrigatório !"}
  validates  :cpf , :presence => {:message => ": é obrigatório !"}

  def cpfcliente
    "#{self.cpf.to_s[0..8]}-#{self.cpf.to_s[9..10]}"
  end

  def telcliente
    "(#{self.tel.to_s[0..2]})#{self.tel.to_s[3..7]}-#{self.tel.to_s[8..11]}"
  end

  def datanacimentocliente
    "#{self.DataNascimento.to_s[8..9]}/#{self.DataNascimento.to_s[5..6]}/#{self.DataNascimento.to_s[0..3]}"
  end

  def self.formatdata(texto)
      "#{texto.to_s[8..9]}/#{texto.to_s[5..6]}/#{texto.to_s[0..3]}"
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index

    case Perm.where("user_id = ?","#{current_user.id}").pluck('cargo').first
    when '3'
      if @clientes = Cliente.where("user_id = ?","#{current_user.id}").present?
        @clientes = Cliente.where("user_id = ?","#{current_user.id}").order("nome asc") 
        if params[:nome]
          @clientes = Cliente.where("nome ilike ? and user_id = ?","%#{params[:nome]}%","#{current_user.id}").order("nome asc") 
        elsif params[:cpf]
          @clientes = Cliente.where("cpf like ? and user_id = ?","%#{params[:cpf]}%","#{current_user.id}").order("nome asc") 
        else
          @clientes = Cliente.where("user_id = ?", "#{current_user.id}").order("nome asc") 
        end
      else
        flash[:notice] =  "Não há Clientes!"
        @clientes = Cliente.where("user_id = ?","#{current_user.id}").order("nome asc") 
      end
    when '2'
      if @clientes = Cliente.where("user_id = ?","#{current_user.id}").present?
        @clientes = Cliente.where("user_id = ?","#{current_user.id}").order("nome asc") 
        if params[:nome]
          @clientes = Cliente.where("nome ilike ? and user_id = ?","%#{params[:nome]}%","#{current_user.id}").order("nome asc") 
        elsif params[:cpf]
          @clientes = Cliente.where("cpf like ? and user_id = ?","%#{params[:cpf]}%","#{current_user.id}").order("nome asc") 
        else
          @clientes = Cliente.where("user_id = ?", "#{current_user.id}").order("nome asc") 
        end
      else
        flash[:notice] =  "Não há Clientes!"
        @clientes = Cliente.where("user_id = ?","#{current_user.id}").order("nome asc") 
      end
    else
      @clientes = Cliente.all 
      if params[:nome]
        @clientes = Cliente.where("nome ilike ? ","%#{params[:nome]}%").order("nome asc") 
      elsif params[:cpf]
        @clientes = Cliente.where("cpf like ? ","%#{params[:cpf]}%").order("nome asc") 
      else
        @clientes = Cliente.all.order("nome asc")
    end
end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @notice = Notice.new
    documento_id = Documento.select(:id).where(cliente_id: params[:id]).pluck(:id)
    @documentos = Documento.find(documento_id)    
    @users = User.all
    #@items =
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)
    Log.create(frase: 'Cadastrou um novo Cliente!',user_id: current_user.id,form: 'CLIENTE',idacao: "#{Cliente.all.pluck("max(id)").first + 1}")
    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    Log.create(frase: 'Alterou o cadastro de um Cliente',user_id: current_user.id,form: 'CLIENTE',idacao: @cliente.id)
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf, :tel, :matricula, :DataNascimento, :Obs, :senhaccheque,:user_id,:atendimento_id)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_documentos.html.erb
<h4>Anexar documentos</h4>
<div class="modal-body">
  <%= form_with(model: [ @cliente, @cliente.documentos.build ], local: true) do |f| %>
    <%= f.hidden_field :cliente_id, value: @cliente.id%>
    <div class="col-sm-12">
      <%= f.label :descricao%>
      <%= f.text_field :nome_documento, class: 'form-control' %>
    </div>
    <div class="col-sm-12">
      <%= f.label :Obs%>
      <%= f.text_field :obs_documento, class: 'form-control' %>
    </div>
    <div class="col-sm-2">
      <%= f.label :Documento%>
      <%= f.file_field :doc %>
    </div>
  </div>
  <div class="actions">   
    <%= f.submit 'Anexar Doc.',:class => 'btn btn-sm btn-success btn-round' %>
  <% end %>
</div><br><br><br>
<h4>Documentos</h4>
<br>
<% @documentos.each do |documento|%>
  <div class="btn-group" role="group">
    <!-- Button trigger modal -->
    <button type="button" class="col-sm-12 btn btn-sm btn-primary" data-toggle="modal" data-target="#<%= documento.id%>">
      <%= documento.nome_documento%>
    </button>
    <%= form_tag(cliente_path, :method => :get) do%>
      <%= hidden_field_tag 'documento',documento.id%>
      <%= hidden_field_tag 'cliente',@cliente.id%>
      <button type="submit" class="btn btn-sm btn-danger">
        <i class="mdi mdi-close"></i>
      </button>
    <%end%>
  </div>
  <br>
  <br>
  <!-- Modal -->
  <div class="modal fade" id="<%= documento.id%>" tabindex="-1" role="dialog" aria-labelledby="<%= documento.id%>Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="<%= documento.id%>Label"> <%= documento.nome_documento%></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= image_tag documento.doc, style: 'height:100%;width:100%;' if documento.doc.attached? %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-success">Abrir PDF</button>
        </div>
      </div>
    </div>
  </div>
<%end%>
<br>

app/views/clientes/_exibir.html.erb
 
<div class="tab-content" id="v-pills-tabContent">
  <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
    <p>
      <strong>Cpf:</strong>
      <%= @cliente.cpfcliente %>
    </p>
    <p>
      <strong>Telefone:</strong>
      <%= @cliente.telcliente %>
    </p>
    <p>
      <strong>Matricula:</strong>
      <%= @cliente.matricula %>
    </p>
    <p>
      <strong>Data nascimento:</strong>
      <%= @cliente.datanacimentocliente %>
    </p>
    <p>
      <strong>Obs:</strong>
      <%= @cliente.Obs %>
    </p>
  </div>
  <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
    <%= render 'clientes/protocolos'%>
  </div>
  <div class="tab-pane fade text-center" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
    <%if @cliente.entradas.present?%>
      <h1>Entradas</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Data da Entrada</th>
            <th>Valor</th>
            <th>Status</th>
            <th>Corretor</th>
            <th>Gerente</th>
            <th colspan="3">Ações</th>
          </tr>
        </thead>
        <tbody>
          <% Entrada.where("cliente_id = ?","#{@cliente.id}").each do |entrada|%>
            <tr>
              <td>
                <%= "#{entrada.dataentrada.to_s[8..9]}/#{entrada.dataentrada.to_s[5..6]}/#{entrada.dataentrada.to_s[0..3]}" %>
              </td>
              <td>
                <%= " #{entrada.valor}"  %>
              </td>
              <td>
                <%= entrada.pago %>
              </td>
              <td>
                <%= User.where("id = ?","#{entrada.idcorretor}").pluck("nome").first%>
              </td>
              <td>
                <%= User.where("id = ?","#{Perm.where("user_id = ?","#{entrada.idcorretor}").pluck("idgerente").first}").pluck("nome").first%>
              </td>
              <td>
                <%= entrada.idgerente %>
              </td>
              <td>
                <%= link_to 'Exibir', entrada, :class=>'btn btn-sm btn-rounded btn-gradient-warning' %>
              </td>
              <td>
                <%= link_to 'Editar', edit_entrada_path(entrada), :class=>'btn  btn-sm btn-rounded btn-gradient-info' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <%else%>
      O Financeiro do Contrato de
      <%=@cliente.nome.titleize%> não foi gerado!
      <button type="button" class="btn btn-gradient-info" data-toggle="modal" data-target="#exampleModalCenter">
        Gerar Financeiro Manual!
      </button>
      <!-- Modal -->
      <div class="modal fade " id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered " role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title " id="exampleModalCenterTitle">Gerar Financeiro
              </h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body text-left">
              <%= form_with(model: [ @cliente, @cliente.entradas.build ], local: true) do |form| %>
                <%= form.hidden_field :cliente_id %>
                <div class="field">
                  <strong><%= form.label :Banco %></strong>
                  <%= collection_select(:entrada,:banco_id,Banco.all,:id,:nome) %>
                </div>
                <div class="field">
                  <strong> <%= form.label :data_entrada %></strong>
                  <%= form.date_field :dataentrada %>
                </div>
                <div class="field">
                  <strong><%= form.label :resumo_da_operação %></strong>
                  <%= form.text_field :resumooperacao %>
                </div>
                <div class="field">
                  <strong>   <%= form.label :valor %> </strong>
                  <%= form.text_field :valor %>
                </div>
                <div class="field">
                  <strong> <%= form.label :Status %></strong>
                  <%= form.select :pago,[["Em Aberto"]] %>
                </div>
                <div class="field">
                  <strong><%= form.label :idcorretor %></strong>
                  <%= form.select :idcorretor, @users.collect { |user| ["#{user.nome}" , user.id] } %>
                </div>
                <div class="field">
                  <strong>   <%= form.label :cliente_id %></strong>
                  <%= form.text_field :cliente_id %>
                </div>
                <form class="forms-sample">
                  <%= form.submit :class=>'btn btn-rounded btn-gradient-primary' %>
                <%end%>
              </form>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
   <div class="tab-pane fade " id="v-pills-doc" role="tabpanel" aria-labelledby="v-pills-doc-tab">
   <%= render 'clientes/documentos'%>
</div>
  <div class="tab-pane fade " id="v-pills-atendimento" role="tabpanel" aria-labelledby="v-pills-atendimento-tab">
    <%= form_with(model: [ @cliente, @cliente.itematendimentoclientes.build ], local: true) do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :cliente_id, value: @cliente.id %>
      <div class="row">
        <div class="col-sm-3">
          <strong>Quando ligou</strong>
          <%= form.date_field :quandoligou, :class=>"form-group form-control" %>
        </div>
        <div class="col-sm-3">
          <strong>Quando irá ligar</strong>
          <%= form.date_field :quandoiraligar, :class=>"form-group form-control" %>
        </div>
        <div class="col-sm-3">
          <strong>Número 1</strong>
          <%= form.number_field :numero1, :class=>"form-group form-control" %>
        </div>
        <div class="col-sm-3">
          <strong>Número 2</strong>
          <%= form.number_field :numero2,:type=>"number",:class=>"form-group form-control" %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <strong>Observação</strong>
          <%= form.text_field :obs, :type =>'text',:class=>'form-control', :placeholder=>'Observação'%>
        </div>
      </div>
      <br>
      <br>
      <div class="row">
        <div class="col-sm-2">
          <%= form.submit :class=>'btn btn-primary' %>
        </div>
      </div>
    <%end%>
    <br>
    <br>
    <%if Itematendimentocliente.where("cliente_id = ?","#{@cliente.id}").present?%>
      <card class="card bg-primary">
        <card class="card-body">
          <table class="table  text-light">
            <thead>
              <tr>
                <th><strong>Quando ligou</strong></th>
                <th><strong>Quando irá ligar</strong></th>
                <th><strong>Número 1</strong></th>
                <th><strong>Obs</strong></th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% Itematendimentocliente.where("cliente_id = ?","#{@cliente.id}").each do |item|%>
                <tr>
                  <td>
                    <%= "#{item.quandoligou.to_s[8..9]}/#{item.quandoligou.to_s[5..6]}/#{item.quandoligou.to_s[0..3]}"  %>
                  </td>
                  <td>
                    <%= "#{item.quandoiraligar.to_s[8..9]}/#{item.quandoiraligar.to_s[5..6]}/#{item.quandoiraligar.to_s[0..3]}" %>
                  </td>
                  <td>
                    <%= simple_format item.numero1 %>
                  </td>
                  <td class="text-black">
                    <button type="button" class="btn btn-gradient-light" data-toggle="modal" data-target="#a<%= item.id%>">
                      Observação
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="a<%= item.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="<%= item.id%>">Observação</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <p><%= simple_format item.obs%></p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </td>
                </tr>
              <%end%>
            </table>
          <%end%>
        </card>
      </card>
    </card>
  </card>
</div>
<div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">...</div>
</div>
</div>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div class = 'card-body erro text-light'id="error_explanation">
      <a href="#" onclick="document.getElementById('erro').style.display='none';">[Fechar]</a>
      Há <%= pluralize(cliente.errors.count, "") %> erro(s) faltou informar o(s) seguinte(s) campo(s):
      <ul >
        <% cliente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :user_id , value: current_user.id%>
  <form class="forms-sample">
    <div class="form-group">
      <label for="exampleInputName1">Nome</label>
      <%= form.text_field :nome, :type =>'text',:class=>'form-control', :placeholder=>'Nome Completo' %>
    </div>
    <div class="form-group">
      <label for="exampleInputName1">Data de Nascimento</label><br>
      <%= form.date_field :DataNascimento %>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail3">CPF</label>
      <%= form.text_field :cpf, :type =>'text',:class=>'form-control', :placeholder=>'CPF sem Pontuação' %>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword4">E-mail</label>
      <%= form.text_field :email, :type =>'text',:class=>'form-control', :placeholder=>'E-mail' %>
    </div>
    <div class="form-group">
      <label for="exampleSelectGender">Telefone</label>
      <%= form.text_field :tel, :type =>'text',:class=>'form-control', :placeholder=>'Telefone sem Formatação' %>
    </div>
    <div class="form-group">
      <label for="exampleSelectGender">Senha do Contra Cheque</label>
      <%= form.text_field :senhaccheque, :type =>'text',:class=>'form-control', :placeholder=>'Senha do Contra Cheque' %>
    </div>
    <div class="form-group">
      <label for="exampleSelectGender">Matricula</label>
      <%= form.text_field :matricula, :type =>'text',:class=>'form-control', :placeholder=>'Matricula' %>
    </div>    
    <div class="form-group">
      <label for="exampleTextarea1">Observação</label>
      <%= form.text_area :Obs, :type =>'text',:class=>'form-control', :placeholder=>'Observação', :id=>'exampleTextarea1', :rows=>'4' %>
    </div>
    <div class="actions">
      <%= form.submit :class=>'btn btn-gradient-primary mr-2' %><%= link_to 'Back', clientes_path, :class=>'btn btn-gradient-danger mr-2' %>
    </div>
  </form>
</div>
</div>
<% end %>

app/views/clientes/edit.html.erb
<div class="card">
                 <div class="card-body">
                   <h4 class="card-title ">Editando Cliente</h4>
                   <p class="card-description"></p>

<%= render 'form', cliente: @cliente %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
<h3 class="page-title">
<span class="page-title-icon bg-gradient-primary text-white mr-2">
<i class="mdi mdi-home"></i>
</span>Lista de Clientes <%= link_to 'Novo Cliente', new_cliente_path , :class=>'btn btn-sm btn-gradient-primary',:"data-turbolinks" => false %></h3>
</div>

<div class="card table-resposive">
  <div class="card-body">                   
<table class ="table table-hover" id="datatable">
  <thead>
    <tr>
      <th>id</th>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Telefone</th>
      <th>Data de Nascimento</th>
      <th>Progresso</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.id %></td>
        <td><%= cliente.nome.upcase %></td>
        <td><%= cliente.cpfcliente %></td>
        <td><%= cliente.telcliente %></td>
        <td><%= cliente.datanacimentocliente %></td>
        <td>
          <%if Protocolo.where("cliente_id = ?","#{cliente.id}").pluck("id").first.present?%>
          <div class="progress">
            <div class="progress-bar bg-primary progress-bar-striped" role="progressbar" style="width: <%= Statusprotocolo.where("protocolo_id = ?","#{Protocolo.where("cliente_id = ?","#{cliente.id}").pluck("id").first}").pluck("progress").first %>%" aria-valuenow="<%= Statusprotocolo.where("protocolo_id = ?","#{Protocolo.where("cliente_id = ?","#{cliente.id}").pluck("id").first}").pluck("progress").first %>" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <%else%>
          <%end%>
        </td>
        <td><%= link_to 'Show', cliente , :class=>'btn btn-sm btn-gradient-warning' %>
        <%= link_to 'Edit',edit_cliente_path(cliente), :class=>'mdi mdi-pencil btn btn-sm btn-gradient-info' %></td>
        <!--td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div></div>

<script type="text/javascript">
  $('#myModal').on('shown.bs.modal', function () {
  $('#myInput').trigger('focus')
})

$('#exampleModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('whatever') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-title').text('New message to ' + recipient)
  modal.find('.modal-body input').val(recipient)
})
</script>


<script type="text/javascript">
$(document).ready( function () {
    $('#datatable').DataTable();
} );
</script>

app/views/clientes/new.html.erb
<div class="card">
                 <div class="card-body">
                   <h4 class="card-title ">Novo Cliente</h4>
                   <p class="card-description"></p>
<%= render 'form', cliente: @cliente %>

app/views/clientes/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<style>
  .nav-pills .nav-link.active, .nav-pills .show > .nav-link {
      color: #fff;
      background-color: #8DC74C;
  }
  .btn-inverse-primary {
      background-color: rgba(141, 199, 76, 0.2);
      }
  
  .btn-inverse-primary.focus, .btn-inverse-primary:focus {
      -webkit-box-shadow: 0 0 0 3px rgba(141, 199, 76, 0.5);
      box-shadow: 0 0 0 3px rgba(141, 199, 76, 0.5);
  }
  .modal-content {
    width: 150%
    }
</style>
<div class="page-header">
  <h3 class="page-title">
    <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-home"></i>
    </span> Cliente: <%= @cliente.nome.titleize %>
    <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      Feedback
    </a>
  </h3>
  <nav aria-label="breadcrumb">
    <ul class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">
        <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
      </li>
    </ul>
  </nav>
</div>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    <%= form_with(model: @notice, local: true, id:@cliente.id) do |form| %>
      <%= form.hidden_field :lido, :value=>"N"%>
      <%= form.hidden_field :acao_id,:value=>"#{@cliente.id}" %>
      <%= form.hidden_field :form, :value=>"clientes" %>
      <%= form.hidden_field :user_id, :value=> "#{current_user.id}" %>
      <%= form.hidden_field :user_destino, :value=> "#{@cliente.user_id}" %>
      <div class="field">
        <%= form.label :mensagem %><br>
        <%= form.text_area :mensagem,class:'form-control' %><br>
      </div>
    <%end%>
    <button class="btn btn-inverse-primary btn-sm" onclick="feedback()">
      Postar
    </button>
  </div>
  <br>
</div>
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-3">
        <%= render 'clientes/navs'%>
      </div>
      <div class="col-9">
        <%= render 'clientes/exibir'%>
      </div>
      <div class="footer-card">
        <%= link_to 'Editar', edit_cliente_path(@cliente), :class=>'btn btm-sm btn-gradient-info float-left'  %>
        <%= link_to 'Voltar', clientes_path, :class=>'btn btm-sm btn-gradient-danger float-right' %>
      </div>
    </div>
  </div>
  <script>
    function feedback() {
      if ( $.ajax({
    type: 'POST',
    url: '../notices',
    data: $('#<%=@cliente.id%>').serialize(),
    dataType: 'JSON'})) {
          Swal.fire({
        icon: 'success',
        title: 'Feedback Enviado!',
        showConfirmButton: false,
        timer: 1500
      });
      $('#notice_mensagem').val('')         
      }else{
          Swal.fire({
        icon: 'error',
        title: 'Feedback não Enviado!',
        showConfirmButton: false,
        timer: 1500
      }); 
      };    
    };
  </script>