config/routes.rb
Rails.application.routes.draw do

  resources :notices
  resources :documentos
  resources :feedbacktologs
  get 'acompanhamento_gerente/index'
  resources :feedbacks
  resources :posts
  resources :logs
  resources :itematendimentoclientes
  get 'ranking/index'
  resources :itematendimentos
  resources :atendimentos do
    resources :itematendimentos
    resources :clientes
  end
  resources :itemsolics
  resources :solicitacoes do
    resources :itemsolics
  end
  resources :movfins
  resources :saidas
  resources :entradas
  get 'relacaocontratos/index'
  resources :statusprotocolos do
    resources :saidas
  end
  resources :perms
  resources :dados
  devise_for :users, :path_prefix => 'login'
  resources :users do
      resources :perms
      resources :dados
  end
  resources :permissoes
  resources :protocolos do
    resources :feedbacks
    resources :statusprotocolos
  end
  resources :bancos
  resources :clientes do
    resources :documentos
    resources :feedbacks
    resources :itematendimentoclientes
    resources :entradas
    resources :protocolos do
      resources :feedbacks
      resources :statusprotocolos do
        resources :saidas
      end
    end
  end
  root 'paginainicial#index'
  get 'paginainicial/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/saida.rb
class Saida < ApplicationRecord
  belongs_to :banco
  has_one_attached :comprovante
  usar_como_dinheiro :valor

  after_update do
    case  self.pago
    when 'Pago'
    movfin = Movfin.new
    movfin.idmov= self.id
    movfin.tipo= 'Saida'
    movfin.acao= "Pagamento"
    movfin.valor= self.valor
    movfin.save
    when 'Extorno'
    movfin = Movfin.new
    movfin.idmov= self.id
    movfin.tipo= 'Saida'
    movfin.acao= "Extorno de Pagamento"
    movfin.valor= self.valor*-1
    movfin.save
    end
  end
end

app/controllers/saidas_controller.rb
class SaidasController < ApplicationController
  before_action :set_saida, only: [:show, :edit, :update, :destroy]

  # GET /saidas
  # GET /saidas.json
  def index
    if params[:datainisearch] and params[:datafinsearch]
      @saidas = Saida.where("datasaida between ? and ?","#{params[:datainisearch]}","#{params[:datafinsearch]}")
      @totalpago = Saida.where("datasaida between ? and ? and pago = 'Pago'","#{params[:datainisearch]}","#{params[:datafinsearch]}").sum("valor")
      @totalinativo = Saida.where("datasaida between ? and ?  and pago = 'Inativo'","#{params[:datainisearch]}","#{params[:datafinsearch]}").sum("valor")
      @totalextorno = Saida.where("datasaida between ? and ?  and pago = 'Extorno'","#{params[:datainisearch]}","#{params[:datafinsearch]}").sum("valor")
    else
      @saidas = Saida.all
      @totalpago = Saida.where("pago = 'Pago'").sum("valor")
      @totalinativo = Saida.where("pago = 'Inativo'").sum("valor")
      @totalextorno = Saida.where("pago = 'Extorno'").sum("valor")
    end

    if params[:datainipdf] and params[:datafinpdf] and params[:gerar_pdf]
      @saidas = Saida.where("datasaida between ? and ?","#{params[:datainipdf]}","#{params[:datafinpdf]}")
      @totalpago = Saida.where("datasaida between ? and ? and pago = 'Pago'","#{params[:datainipdf]}","#{params[:datafinpdf]}").sum("valor")
      @totalinativo = Saida.where("datasaida between ? and ?  and pago = 'Inativo'","#{params[:datainipdf]}","#{params[:datafinpdf]}").sum("valor")
      @totalextorno = Saida.where("datasaida between ? and ?  and pago = 'Extorno'","#{params[:datainipdf]}","#{params[:datafinpdf]}").sum("valor")
      render pdf:"Saidas",
      page_size: 'A4',
      template: "saidas/index.pdf.erb",
      layout:"pdf.html",
      lowquality: true,
      zoon: 1,
      dpi: 75
    end
    @users = User.all
  end

  # GET /saidas/1
  # GET /saidas/1.json
  def show
  end

  # GET /saidas/new
  def new
    @clientes = Cliente.all
    @users = User.all
    @bancos = Banco.all
    @saida = Saida.new
  end

  # GET /saidas/1/edit
  def edit
     @bancos = Banco.all
     @users= User.all
  end

  # POST /saidas
  # POST /saidas.json
  def create
    @clientes = Cliente.all
    @users = User.all
    @bancos = Banco.all
    @saida = Saida.new(saida_params)
    Log.create(frase: 'Lançou uma Saida',user_id: current_user.id,form: 'SAIDA',idacao: "#{Saida.all.pluck("max(id)").first + 1}")
    respond_to do |format|
      if @saida.save
        format.html { redirect_to @saida, notice: 'Saida was successfully created.' }
        format.json { render :show, status: :created, location: @saida }
      else
        format.html { render :new }
        format.json { render json: @saida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saidas/1
  # PATCH/PUT /saidas/1.json
  def update
    Log.create(frase: 'Alterou uma Saida',user_id: current_user.id,form: 'SAIDA',idacao: @saida.id)
    respond_to do |format|
      if @saida.update(saida_params)
        format.html { redirect_to @saida, notice: 'Saida was successfully updated.' }
        format.json { render :show, status: :ok, location: @saida }
      else
        format.html { render :edit }
        format.json { render json: @saida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saidas/1
  # DELETE /saidas/1.json
  def destroy
    @saida.destroy
    respond_to do |format|
      format.html { redirect_to saidas_url, notice: 'Saida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saida
      @saida = Saida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saida_params
      params.require(:saida).permit(:banco_id, :datasaida, :resumooperacao, :valor, :pago, :idcorretor, :idgerente, :cliente_id,:comprovante)
    end
end

app/helpers/saidas_helper.rb
module SaidasHelper
end

app/views/saidas/_form.html.erb
<%= form_with(model: saida, local: true) do |form| %>
  <% if saida.errors.any? %>
    <div class = "erro card bg-danger" id="error_explanation">
      <h2><%= pluralize(saida.errors.count, "error") %> prohibited this saida from being saved:</h2>

      <ul>
        <% saida.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">
        <div class="field">
          <strong><%= form.label :banco_id %><br></strong>
          <%= form.select :banco_id, @bancos.collect { |banco| [banco.nome, banco.id] } , :class=>"form-control form-control-sm", :id=>"exampleFormControlSelect1"%>
        </div>
      </th>
      <th scope="col">
        <div class="field">
          <strong>  <%= form.label :Data_saida %><br></strong>
          <%= form.date_field :datasaida %>
        </div>
      </th>
      <th scope="col">
        <div class="field">
          <%case @saida.pago%>
          <%when "Em aberto"%>
          <strong>Pagar/Inativar<br></strong>
          <%= form.select :pago, [["Pago"],["Inativo"]] %>
          <%when "Pago"%>
          <strong><%= form.label :pago %><br></strong>
          <%= form.select :pago, [["Extorno"]] %>
          <%when "Extorno"%>
          <strong><%= form.label :pago %><br></strong>
          <%= form.select :pago, [["Pago"],["Inativo"]] %>
          <%end%>
        </div>
      </th>
    </tr>
  </thead>
  </table>

  <%case @saida.pago%>
    <%when "Pago"%>
    <div class="field">
      <strong>  <%= form.label :valor %><br></strong>
      <div class="input-group-prepend">
        <span class="input-group-text bg-gradient-primary text-white">$</span><strong class="text-primary" > <h3>R$ <%= @saida.valor%></h3></strong>
      </div>
    </div>
    <%when "Em aberto"%>
    <div class="field">
      <strong>  <%= form.label :valor %><br></strong>
      <div class="input-group-prepend">
        <span class="input-group-text bg-gradient-primary text-white">$</span><strong class="text-primary" > <h3>R$ <%= @saida.valor%></h3></strong>
      </div>
    </div>
    <%when ""%>
    <div class="field">
      <strong>  <%= form.label :valor %><br></strong>
      <div class="input-group-prepend">
        <span class="input-group-text bg-gradient-primary text-white">$</span>
        <%= form.number_field :valor, :type =>'number',:class=>'form-control', :placeholder=>'Valor' %>
      </div>
    </div>
    <%when "Inativo"%>
    <div class="field">
      <strong>  <%= form.label :valor %><br></strong>
      <div class="input-group-prepend">
        <span class="input-group-text bg-gradient-primary text-white">$</span>
        <%= form.number_field :valor, :type =>'number',:class=>'form-control', :placeholder=>'Valor' %>
      </div>
    </div>
    <%else%>
    <div class="field">
      <strong>  <%= form.label :valor %><br></strong>
      <div class="input-group-prepend">
        <span class="input-group-text bg-gradient-primary text-white">$</span>
        <%= form.number_field :valor, :type =>'number',:class=>'form-control', :placeholder=>'Valor' %>
      </div>
    </div>
  <%end%>

  <div class="field">
    <strong> <%= form.label :resumo_da_operação %><br></strong>
    <%= form.text_area :resumooperacao, :type =>'text',:class=>'form-control', :placeholder=>'Valor da Parcela' %>
  </div>


    <div class="field">
      <strong>Corretor:</strong><br>
      <%= form.select :idcorretor, @users.collect { |user| [user.nome, user.id] },{:include_blank => ''}, :class => 'form-control' %>
    </div>

 <div class="field">
      <strong>Gerente:</strong><br>
      <%= form.select :idgerente, @users.collect { |user| [user.nome, user.id] } ,{:include_blank => ''} , :class => 'form-control'%>
</div>
    <div class="field">
      <strong>Cliente:</strong><br>
      <%= form.select :cliente_id, @clientes.collect { |cliente| [cliente.nome, cliente.id] } ,{:include_blank => ''}, :class => 'form-control' %>
    </div>
  <br>
  <div class="actions">
    <%= form.submit :class=>'btn btn-gradient-primary' %>
  </div>
  <%end%>

app/views/saidas/edit.html.erb
<card class="card">
  <card class="card-body">
    <h4 class="card-title ">Lançando Pagamento</h4>
    <%= form_with(model: @saida, local: true) do |form| %>
      <% if @saida.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@saida.errors.count, "error") %> prohibited this saida from being saved:</h2>

          <ul>
            <% @saida.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <table class="table">
      <thead>
        <tr>
          <th scope="col">
            <div class="field">
              <strong><%= form.label :banco_id %><br></strong>
              <%= form.select :banco_id, @bancos.collect { |banco| [banco.nome, banco.id] } , :class=>"form-control form-control-sm", :id=>"exampleFormControlSelect1"%>
            </div>
          </th>
          <th scope="col">
            <div class="field">
              <strong>  <%= form.label :Data_saida %><br></strong>
              <%= form.date_field :datasaida %>
            </div>
          </th>
          <th scope="col">
            <div class="field">
              <%case @saida.pago%>
              <%when "Em aberto"%>
              <strong>Pagar/Inativar<br></strong>
              <%= form.select :pago, [["Pago"],["Inativo"]] %>
              <%when nil%>
              <strong>Pagar/Inativar<br></strong>
              <%= form.select :pago, [["Pago"],["Inativo"]] %>
              <%when "Pago"%>
              <strong><%= form.label :pago %><br></strong>
              <%= form.select :pago, [["Extorno"]] %>
              <%when "Extorno"%>
              <strong><%= form.label :pago %><br></strong>
              <%= form.select :pago, [["Pago"],["Inativo"]] %>
              <%end%>
            </div>
          </th>
        </tr>
      </thead>
      </table>

      <%case @saida.pago%>
        <%when "Pago"%>
        <div class="field">
          <strong>  <%= form.label :valor %><br></strong>
          <div class="input-group-prepend">
            <span class="input-group-text bg-gradient-primary text-white">$</span><strong class="text-primary" > <h3>R$ <%= @saida.valor%></h3></strong>
          </div>
        </div>
        <%when "Em aberto"%>
        <div class="field">
          <strong>  <%= form.label :valor %><br></strong>
          <div class="input-group-prepend">
            <span class="input-group-text bg-gradient-primary text-white">$</span><strong class="text-primary" > <h3>R$ <%= @saida.valor%></h3></strong>
          </div>
        </div>
        <%when ""%>
        <div class="field">
          <strong>  <%= form.label :valor %><br></strong>
          <div class="input-group-prepend">
            <span class="input-group-text bg-gradient-primary text-white">$</span>
            <%= form.number_field :valor, :type =>'number',:class=>'form-control', :placeholder=>'Valor' %>
          </div>
        </div>
        <%when "Inativo"%>
        <div class="field">
          <strong>  <%= form.label :valor %><br></strong>
          <div class="input-group-prepend">
            <span class="input-group-text bg-gradient-primary text-white">$</span>
            <%= form.number_field :valor, :type =>'number',:class=>'form-control', :placeholder=>'Valor' %>
          </div>
        </div>
        <%else%>
        <div class="field">
          <strong>  <%= form.label :valor %><br></strong>
          <div class="input-group-prepend">
            <span class="input-group-text bg-gradient-primary text-white">$</span>
            <%= form.number_field :valor, :type =>'number',:class=>'form-control', :placeholder=>'Valor' %>
          </div>
        </div>
      <%end%>

      <div class="field">
        <strong> <%= form.label :resumo_da_operação %><br></strong>
        <%= form.text_area :resumooperacao, :type =>'text',:class=>'form-control', :placeholder=>'Valor da Parcela' %>
      </div>

<br>
        <div class="field">

          <%if @saida.idcorretor.present? %>
          <strong>Corretor:</strong>
          <%= User.where("id = ?","#{@saida.idcorretor}").pluck("nome").first%>
          <%else%>
          <%end%>
<br>
          <%if @saida.idgerente.present? %>
        <strong>Gerente:</strong><br>
          <%= User.where("id = ?","#{@saida.idgerente}").pluck("nome").first %>
          <%else%>
          <%end%>

        </div>
<br>
<%if @saida.cliente_id.present?%>
        <div class="field">
          <strong>Cliente:</strong><br>
          <%= Cliente.where("id = ?","#{@saida.cliente_id}").pluck("nome").first %>
        </div>
        <%else%>
<%end%>
        <div class="field">
        <strong>Comprovante:</strong><br>
        <%= form.file_field :comprovante%>
        </div>
      <br>
      <div class="actions">
        <%= form.submit :class=>'btn btn-gradient-primary' %>
      </div>
      <%end%>


</card>
</card>

app/views/saidas/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
<h3 class="page-title">
<span class="page-title-icon bg-gradient-primary text-white mr-2">
<i class="mdi mdi-home"></i>
</span> Lista de saidas <%= link_to 'Nova saida', new_saida_path, class:'btn btn-gradient-primary btn-sm' %>
<button type="button" class="btn btn-gradient-success btn-sm" data-toggle="modal" data-target="#rel">
Relatorio
</button>
  <button type="button" class="btn btn-gradient-info btn-sm" data-toggle="modal" data-target="#buscar">
Filtros p/ pesquisa
</button>  
<button class="btn btn-gradient-danger btn-sm" type="button" data-toggle="collapse" data-target="#mes" aria-expanded="false" aria-controls="collapseExample">
  Lançamentos dos meses
</button></h3>
<nav aria-label="breadcrumb">
<ul class="breadcrumb">
<li class="breadcrumb-item active" aria-current="page">
<span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
</li>
</ul>
</nav>
</div>




<div class="collapse row" id="mes">
<% ['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'].each do |mes|%>

<div class="col-sm-2">
<div class="card">
<div class=" card-header">
<%= mes%>
 </div>
  <div class=" card-body">
   <h6>Vlr. do mês:</h6><br>
   <h6>R$</h6>
    <button type="button" class="btn btn-gradient-warning btn-sm">
      Detalhes
    </button> 
  </div>

</div>
  <br>
</div>

<%end%>
</div>

<br>
<card class="card">
  <card class="card-body">
<!-- Modal -->
  <div class="modal fade " id="rel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title " id="exampleModalCenterTitle">Adicionando Filtros p/ Relatorio
          </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <div class="modal-body text-left">
        <form class="forms-sample">
          <%= form_tag(saidas_path, :method => :get) do%>
          Data Inicial
          <%= date_field 'datainipdf',nil, :class => 'form-control'%>
          Data Final
          <%= date_field 'datafinpdf',nil, :class => 'form-control'%>
          <%= hidden_field 'gerar_pdf',nil,:class => 'form-control'%>

          <%= submit_tag "Pesquisar", :class => 'btn btn-success btn-round',:target=>'_blank' %>
          <%end%>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
  <div class="modal fade " id="buscar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title " id="exampleModalCenterTitle">Adicionando Filtros p/ Pesquisa
          </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <div class="modal-body text-left">
        <form class="forms-sample">
          <%= form_tag(saidas_path, :method => :get) do%>
          Data Inicial
          <%= date_field 'datainisearch',nil, :class => 'form-control'%>
          Data Final
          <%= date_field 'datafinsearch',nil, :class => 'form-control'%>
          Tipo
          <%= select_tag 'paraquem', options_for_select(["Saida","saida"]), :class => 'form-control'%>

          <%= submit_tag "Pesquisar", :class => 'btn btn-success btn-round' %>
          <%end%>
        </form>
      </div>
    </div>
  </div>
</div>


<table class="table table-bordered table-sm table-bordered " id ="datatable">
  <thead>
    <tr class="bg-primary text-center">
      <th scope="col"><strong>N° saida:</strong> </th>
      <th scope="col"><strong>Corretor/Gerente: </strong></th>
      <th scope="col"><strong>Data da saida:</strong> </th>
      <th scope="col"><strong>Status:</strong> </th>
      <th scope="col"><strong>Valor: </strong></th>
      <th scope="col"><strong>Ações: </strong></th>
    </tr>
  </thead>
  <tbody>
  <% @saidas.each do |saida| %>
    <tr>
      <td class="text-center"><%= saida.id %></td>
      <td class="text-center"><%if saida.idcorretor.present?%>
          <%= User.where("id = ?","#{saida.idcorretor}").pluck("nome").first %><%else%> <%end%> |<%if saida.idgerente.present?%> <%= User.where("id = ?","#{saida.idgerente}").pluck("nome").first %> <%else%> <%end%></td>
      <td class="text-center"><%= "#{saida.datasaida.to_s[8..9]}/#{saida.datasaida.to_s[5..6]}/#{saida.datasaida.to_s[0..3]}"  %></td>
      <td class="text-center"> <%= saida.pago %> </td>
      <td class="text-center"><%= "R$ #{saida.valor}" %></td>       
    <div class="float-right">
    <td>
    <button type="button" class="btn btn-sm btn-gradient-info" data-toggle="modal" data-target="#s<%= saida.id %>">
      Comprovante
    </button>
      <!-- Modal -->
      <div class="modal fade" id="s<%= saida.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            <%= image_tag saida.comprovante, style: 'height:100%;width:100%;' if  saida.comprovante.attached?%>
            </div>
          </div>
        </div>
      </div>
      <%= link_to 'Movimentar', edit_saida_path(saida),:class=>'btn btn-sm btn-gradient-primary' %>
      <%= link_to 'Exibir', saida_path(saida),:class=>'btn btn-sm btn-gradient-warning' %>
      <%= link_to 'Excluir', saida, method: :delete, data: { confirm: 'Não será apagado se já gerado movimentação financeira!' },:class=>'btn btn-sm btn-gradient-danger' %></div>
	  </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>







    <table>
      <tbody>
      <tr>
       <td class="text-right">Total Pago:</td>
       <td><%="R$ #{@totalpago}" %></td>
       </tr>
       <tr>
       <td class="text-right">Total Inativo:</td>
       <td><%="R$ #{@totalinativo}" %></td>
       </tr>
           <tr>
       <td class="text-right">Total Extornado:</td>
       <td><%="R$ #{@totalextorno}" %></td>
       </tr>
     </tbody>
    </table>

</card>
</card>

<script type="text/javascript">
$(document).ready( function () {
    $('#datatable').DataTable();
} );
</script>

app/views/saidas/new.html.erb
<card class="card">
<card class="card-body">
<h1> Lançar Saida</h1>

<%= render 'form', saida: @saida %>

<%= link_to 'Back', saidas_path %>

</card> 
</card> 

app/views/saidas/show.html.erb
<card class="card">
<card class="card-body">

<p id="notice"><%= notice %></p>
<table class="table table-bordered table-sm table-bordered ">
  <thead>
    <tr class="bg-primary text-center"> 
      <th scope="col"><strong>N° Saída:</strong> </th>
      <th scope="col"><strong>Corretor/Gerente: </strong></th>
      <th scope="col"><strong>Data da Saida:</strong> </th>
      <th scope="col"><strong>Status:</strong> </th>
      <th scope="col"><strong>Valor: </strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="text-center"><%= @saida.id %></td>
      <td class="text-center"><%if @saida.idcorretor.present?%>
          <%= User.where("id = ?","#{@saida.idcorretor}").pluck("nome").first %><%else%> <%end%> |<%if @saida.idgerente.present?%> <%= User.where("id = ?","#{@saida.idgerente}").pluck("nome").first %> <%else%> <%end%></td>
      <td class="text-center"><%= "#{@saida.datasaida.to_s[8..9]}/#{@saida.datasaida.to_s[5..6]}/#{@saida.datasaida.to_s[0..3]}"  %></td>
      <td class="text-center"> <%= @saida.pago %> </td>
      <td class="text-center"><%= "R$ #{@saida.valor}" %></td>
    </tr>
    <tr>  
      <td colspan="5" class="text-left">
      	<strong>Resumo da Operação:</strong><br>
		<%= @saida.resumooperacao %>
	  </td> 
    </tr>
  </tbody>
</table> 
<p>
  <strong>Comprovante:</strong><br>
  <button type="button" class="btn btn-gradient-primary" data-toggle="modal" data-target="#exampleModalCenter">
   Exibir 
</button>
</p>

<!-- Modal -->
<div class="modal fade " id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered " role="document">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title " id="exampleModalCenterTitle">Comprovante
      </h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      </div>
      <div class="modal-body text-left">
        <form class="forms-sample">
        <%= image_tag @saida.comprovante, style: 'height:100%;width:100%;' if  @saida.comprovante.attached?%>
        </form>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Editar', edit_saida_path(@saida),:class=>"btn btn-gradient-info" %> |
<%= link_to 'Voltar', saidas_path,:class=>"btn btn-gradient-danger" %>

</card >
</card >