config/routes.rb
Rails.application.routes.draw do

  resources :notices
  resources :documentos
  resources :feedbacktologs
  get 'acompanhamento_gerente/index'
  resources :feedbacks
  resources :posts
  resources :logs
  resources :itematendimentoclientes
  get 'ranking/index'
  resources :itematendimentos
  resources :atendimentos do
    resources :itematendimentos
    resources :clientes
  end
  resources :itemsolics
  resources :solicitacoes do
    resources :itemsolics
  end
  resources :movfins
  resources :saidas
  resources :entradas
  get 'relacaocontratos/index'
  resources :statusprotocolos do
    resources :saidas
  end
  resources :perms
  resources :dados
  devise_for :users, :path_prefix => 'login'
  resources :users do
      resources :perms
      resources :dados
  end
  resources :permissoes
  resources :protocolos do
    resources :feedbacks
    resources :statusprotocolos
  end
  resources :bancos
  resources :clientes do
    resources :documentos
    resources :feedbacks
    resources :itematendimentoclientes
    resources :entradas
    resources :protocolos do
      resources :feedbacks
      resources :statusprotocolos do
        resources :saidas
      end
    end
  end
  root 'paginainicial#index'
  get 'paginainicial/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/protocolo.rb
class Protocolo < ApplicationRecord
  belongs_to :cliente
  belongs_to :banco
  has_many :statusprotocolos
  has_many :feedbacks
end

app/controllers/protocolos_controller.rb
class ProtocolosController < ApplicationController
  before_action :set_protocolo, only: [:show, :edit, :update, :destroy]

  # GET /protocolos
  # GET /protocolos.json
  def index
    @protocolos = Protocolo.all
  end

  # GET /protocolos/1
  # GET /protocolos/1.json
  def show
  end

  # GET /protocolos/new
  def new
    @protocolo = Protocolo.new
    @users = User.all
  end

  # GET /protocolos/1/edit
  def edit
      @users = User.all
  end

  # POST /protocolos
  # POST /protocolos.json
  def create
    @protocolo = Protocolo.new(protocolo_params)
    Log.create(frase: 'Criou um Protocolo',user_id: current_user.id,form: 'PROTOCOLO',idacao: "#{Protocolo.all.pluck("max(id)").first + 1}")
    respond_to do |format|
      if @protocolo.save
        format.html { redirect_to @protocolo, notice: 'Protocolo was successfully created.' }
        format.json { render :show, status: :created, location: @protocolo }
      else
        format.html { render :new }
        format.json { render json: @protocolo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /protocolos/1
  # PATCH/PUT /protocolos/1.json
  def update
    Log.create(frase: 'Alterou um Protocolo',user_id: current_user.id,form: 'PROTOCOLO',idacao: @protocolo.id)    
    respond_to do |format|
      if @protocolo.update(protocolo_params)
        format.html { redirect_to @protocolo, notice: 'Protocolo was successfully updated.' }
        format.json { render :show, status: :ok, location: @protocolo }
      else
        format.html { render :edit }
        format.json { render json: @protocolo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /protocolos/1
  # DELETE /protocolos/1.json
  def destroy
    @protocolo.destroy
    respond_to do |format|
      format.html { redirect_to protocolos_url, notice: 'Protocolo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_protocolo
      @protocolo = Protocolo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def protocolo_params
      params.require(:protocolo).permit(:valorparcela, :prazo, :valorcontrato, :prestservico, :cliente_id, :banco_id,:idcorretor,:orgao,:tipoemprestimo)
    end
end

app/helpers/protocolos_helper.rb
module ProtocolosHelper
end

app/views/protocolos/_form.html.erb
<%= form_with(model: protocolo, local: true) do |form| %>
  <% if protocolo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(protocolo.errors.count, "error") %> prohibited this protocolo from being saved:</h2>

      <ul>
        <% protocolo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :cliente_id %>
  <form class="forms-sample">
    <div class="form-group">
      <label for="exampleInputEmail3">Banco</label><br>
      <%= collection_select(:protocolo,:banco_id,Banco.all,:id,:nome) %>
    </div>
    <div class="form-group">
      <label for="exampleInputName1">Valor da Parcela (*)</label>
      <%= input_dinheiro_precisao form, :valorparcela, ("Valor da Parcela"),place_holder: "Valor da Parcela" %>
    </div>
    <div class="form-group">
      <label for="exampleInputName1">Prazo (*)</label><br>
        <%= form.number_field :prazo, :type =>'text',:class=>'form-control', :placeholder=>'Prazo' %>
    </div>

    <div class="form-group">
      <label for="exampleInputName1">Corretor(*)</label><br>
    <%= form.select :idcorretor, @users.collect { |user| [user.nome, user.id] } %>
    </div>

    <div class="form-group">
      <label for="exampleInputEmail3">Valor do Contrato</label>
      <%= input_dinheiro_precisao form, :valorcontrato, ("Valor do Contrato"),place_holder: "Digite o Valor do Contrato" %>
    </div>

    <div class="form-group">
      <label for="exampleInputEmail3">Tipo de Emprestimo</label>
      <%= form.select :tipoemprestimo,['Margem livre','Refin','Refin + margem','Portabilidade','Portabilidade com redução de parcela','Compra de dívida','Cartão consignado','Unificação de parcela'], {}, { :class => 'form-control' }%>
    </div>

    <div class="form-group">
      <label for="exampleInputEmail3">Orgão</label>
      <%= form.select :orgao,['Estado','Prefeitura','INSS','Federal','Siape','Aeronautica','Marinha','Exercito'], {}, { :class => 'form-control' }%>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail3">Prestação de Serviço</label>
      <%= input_dinheiro_precisao form, :prestservico, ("Pestação de Serviço"),place_holder: "Digite a Pestação de Serviço" %>
    </div>
   <%= form.submit :class=>'btn btn-rounded btn-gradient-primary' %>
<% end %>

app/views/protocolos/edit.html.erb
<card class="card">
<card class="card-body">
  <h4 class="card-title ">Cliente: <%= Cliente.where("id = ?","#{Protocolo.where("id = ?","#{params[:id]}").pluck("cliente_id").first}").pluck("nome").first.titleize %></h4>
  <p class="card-description"></p>

<%= render 'form', protocolo: @protocolo %>
<br>
<%= link_to 'Back', cliente_path(@protocolo.cliente_id), :class=>'btn btn-gradient-danger btn-rounded' %>

app/views/protocolos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Protocolos</h1>

<table>
  <thead>
    <tr>
      <th>Valorparcela</th>
      <th>Prazo</th>
      <th>Valorcontrato</th>
      <th>Prestservico</th>
      <th>Cliente</th>
      <th>Banco</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @protocolos.each do |protocolo| %>
      <tr>
        <td><%= protocolo.valorparcela %></td>
        <td><%= protocolo.prazo %></td>
        <td><%= protocolo.valorcontrato %></td>
        <td><%= protocolo.prestservico %></td>
        <td><%= protocolo.cliente_id %></td>
        <td><%= protocolo.banco_id %></td>
        <td><%= link_to 'Show', protocolo %></td>
        <td><%= link_to 'Edit', edit_protocolo_path(protocolo) %></td>
        <td><%= link_to 'Destroy', protocolo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Protocolo', new_protocolo_path %>

app/views/protocolos/new.html.erb
<h1>New Protocolo</h1>

<%= render 'form', protocolo: @protocolo %>

<%= link_to 'Back', protocolos_path %>

app/views/protocolos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
<div class="card-body">
<h3> Protocolo de Contrato</h3>
<p>
  <strong>Cliente:</strong>
  <%= Cliente.where("id = ?","#{@protocolo.cliente_id}").pluck("nome").first.titleize%>
</p>
<p>
  <strong>Valor da parcela:</strong>
  <%= "#{@protocolo.valorparcela.to_dinheiro}" %>
</p>

<p>
  <strong>Prazo:</strong>
  <%= @protocolo.prazo %>
</p>

<p>
  <strong>Valor do Contrato:</strong>
  <%= "#{@protocolo.valorcontrato.to_dinheiro}" %>
</p>

<p>
  <strong>Valor da Prestação de Serviço:</strong>
  <%= "#{@protocolo.prestservico.to_dinheiro}" %>
</p>



<p>
  <strong>Banco:</strong>
  <%= "#{Banco.where("id = ?","#{@protocolo.banco_id}").pluck("codigo").first}-#{Banco.where("id = ?","#{@protocolo.banco_id}").pluck("nome").first}" %>
</p>

<% if @protocolo.statusprotocolos.present?%>

<p>
  <strong>Status:</strong>
  <%= @protocolo.statusprotocolos.first.status %> <%= link_to 'Editar', edit_statusprotocolo_path(@protocolo.statusprotocolos.first.id), :class=>'btn btn-rounded btn-gradient-info' %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @protocolo.statusprotocolos.first.obs %>
</p>


<%else%>
<div class="card bg-gradient-danger card-img-holder text-white">
  <div class="card-body">
<%= form_with(model: [ @protocolo, @protocolo.statusprotocolos.build ], local: true) do |form| %>
<div class="field">
  <%= form.hidden_field :protocolo_id %>
</div>
<div class="field">
  <%= form.select :progress, [['0%',0],['25%',25],['50%',50],['75%',75],['90%',90],['100%',100]] %>
</div>
<div class="field">
  <strong><%= form.label :status %></strong>
  <%= form.text_field :status, :type =>'text',:class=>'form-control', :placeholder=>'Status' %>
</div>



<div class="field">
  <strong><%= form.label :Observação %></strong>
  <%= form.text_area :obs, :type =>'text',:class=>'form-control', :placeholder=>'Observação' %>
</div>
<br>
<%= form.submit :class=>'btn btn-rounded btn-danger' %>
</div>
</div>
<%end%>
<%end%>
<br>
<%= link_to 'Voltar para o cliente!', cliente_path(@protocolo.cliente_id) ,:class=>'btn btn-rounded btn-gradient-danger' %>
</div>
</div>