config/routes.rb
Rails.application.routes.draw do

  resources :notices
  resources :documentos
  resources :feedbacktologs
  get 'acompanhamento_gerente/index'
  resources :feedbacks
  resources :posts
  resources :logs
  resources :itematendimentoclientes
  get 'ranking/index'
  resources :itematendimentos
  resources :atendimentos do
    resources :itematendimentos
    resources :clientes
  end
  resources :itemsolics
  resources :solicitacoes do
    resources :itemsolics
  end
  resources :movfins
  resources :saidas
  resources :entradas
  get 'relacaocontratos/index'
  resources :statusprotocolos do
    resources :saidas
  end
  resources :perms
  resources :dados
  devise_for :users, :path_prefix => 'login'
  resources :users do
      resources :perms
      resources :dados
  end
  resources :permissoes
  resources :protocolos do
    resources :feedbacks
    resources :statusprotocolos
  end
  resources :bancos
  resources :clientes do
    resources :documentos
    resources :feedbacks
    resources :itematendimentoclientes
    resources :entradas
    resources :protocolos do
      resources :feedbacks
      resources :statusprotocolos do
        resources :saidas
      end
    end
  end
  root 'paginainicial#index'
  get 'paginainicial/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/perm.rb
class Perm < ApplicationRecord
  belongs_to :user
end

app/controllers/perms_controller.rb
class PermsController < ApplicationController
  before_action :set_perm, only: [:show, :edit, :update, :destroy]

  # GET /perms
  # GET /perms.json
  def index
    @perms = Perm.all
  end

  # GET /perms/1
  # GET /perms/1.json
  def show
  end

  # GET /perms/new
  def new
    @perm = Perm.new
  end

  # GET /perms/1/edit
  def edit
      @users = User.all
  end

  # POST /perms
  # POST /perms.json
  def create
    @perm = Perm.new(perm_params)

    respond_to do |format|
      if @perm.save
        format.html { redirect_to controller:"users",action:"show",id:@perm.user_id, notice: 'Perm was successfully created.' }
        format.json { render :show, status: :created, location: @perm }
      else
        format.html { render :new }
        format.json { render json: @perm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perms/1
  # PATCH/PUT /perms/1.json
  def update
    respond_to do |format|
      if @perm.update(perm_params)
        format.html { redirect_to controller:"users",action:"show",id:@perm.user_id, notice: 'Perm was successfully updated.' }
        format.json { render :show, status: :ok, location: @perm }
      else
        format.html { render :edit }
        format.json { render json: @perm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perms/1
  # DELETE /perms/1.json
  def destroy
    @perm.destroy
    respond_to do |format|
      format.html { redirect_to perms_url, notice: 'Perm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perm
      @perm = Perm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perm_params
      params.require(:perm).permit(:cargo, :comissaogerente, :comissaocorretor, :idgerente, :user_id)
    end
end

app/helpers/perms_helper.rb
module PermsHelper
end

app/views/perms/_form.html.erb
<%= form_with(model: perm, local: true) do |form| %>
  <% if perm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perm.errors.count, "error") %> prohibited this perm from being saved:</h2>

      <ul>
        <% perm.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cargo %><br>
    <%= form.select :cargo,[['Admin',0],['Operacional',1],['Gerente',2],['Corretor',3]] %>
  </div>
<br>
  <div class="field">
    <%= form.label :Gerente %><br>
    <%= form.select :idgerente, @users.collect { |user| [user.nome, user.id] } %>
  </div>
<br>
  <div class="field">
    <%= form.label :comissão_gerente %>
    <%= form.select :comissaogerente, [['1%',1],['2%',2],['3%',3],['4%',4],['5%',5],['6%',6],['7%',7],['8%',8],['9%',9],['10%',10],['11%',11],['12%',12],['13%',13],['14%',14],['15%',15],['16%',16],['17%',17],['18%',18],['19%',19],['20%',20],['21%',21],['22%',22],['23%',23],['24%',24],['25%',25],['26%',26],['27%',27],['28%',28],['29%',29],['30%',30],['31%',31],['32%',32],['33%',33],['34%',34],['35%',35],['36%',36],['37%',37],['38%',38],['39%',39],['40%',40],['41%',41],['42%',42],['43%',43],['44%',44],['45%',45],['46%',46],['47%',47],['48%',48],['49%',49],['50%',50]],:class=>'custom-select' %>
  </div>
<br>
  <div class="field">
    <%= form.label :comissão_corretor %>
    <%= form.select :comissaocorretor, [['1%',1],['2%',2],['3%',3],['4%',4],['5%',5],['6%',6],['7%',7],['8%',8],['9%',9],['10%',10],['11%',11],['12%',12],['13%',13],['14%',14],['15%',15],['16%',16],['17%',17],['18%',18],['19%',19],['20%',20],['21%',21],['22%',22],['23%',23],['24%',24],['25%',25],['26%',26],['27%',27],['28%',28],['29%',29],['30%',30],['31%',31],['32%',32],['33%',33],['34%',34],['35%',35],['36%',36],['37%',37],['38%',38],['39%',39],['40%',40],['41%',41],['42%',42],['43%',43],['44%',44],['45%',45],['46%',46],['47%',47],['48%',48],['49%',49],['50%',50]],:class=>'custom-select' %>
  </div>
<br>
  <div class="field">
    <%= form.label :Observação %>
    <%= form.text_area :obseravacao, :type =>'text',:class=>'form-control', :placeholder=>'Observação' %>
  </div>
<br>
  <%= form.submit :class=>'btn btn-rounded btn-gradient-primary' %> <%= link_to 'Back', user_path(User.where("id = ?","#{Perm.where("id = ?","#{params[:id]}").pluck("user_id").first}").pluck("id").first), :class=>'btn btn-rounded btn-gradient-danger'%>

  <div class="field">
    <%= form.hidden_field :user_id %>
  </div>


<% end %>
</card>
</card>

app/views/perms/edit.html.erb
<card class="card">
<card class="card-body">
  <h4 class="card-title ">Usuário: <%= User.where("id = ?","#{
    Perm.where("id = ?","#{params[:id]}").pluck("user_id").first}").pluck("id").first %></h4>
  <p class="card-description"></p>
  <p>
    <strong>Nome:</strong>
    <%= User.where("id = ?","#{
      Perm.where("id = ?","#{params[:id]}").pluck("user_id").first}").pluck("nome").first %>
  </p>

<%= render 'form', perm: @perm %>

app/views/perms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Perms</h1>

<table>
  <thead>
    <tr>
      <th>Cargo</th>
      <th>Comissaogerente</th>
      <th>Comissaocorretor</th>
      <th>Idgerente</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perms.each do |perm| %>
      <tr>
        <td><%= perm.cargo %></td>
        <td><%= perm.comissaogerente %></td>
        <td><%= perm.comissaocorretor %></td>
        <td><%= perm.idgerente %></td>
        <td><%= perm.user_id %></td>
        <td><%= link_to 'Show', perm %></td>
        <td><%= link_to 'Edit', edit_perm_path(perm) %></td>
        <td><%= link_to 'Destroy', perm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Perm', new_perm_path %>

app/views/perms/new.html.erb
<h1>New Perm</h1>

<%= render 'form', perm: @perm %>

<%= link_to 'Back', perms_path %>

app/views/perms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cargo:</strong>
  <%= @perm.cargo %>
</p>

<p>
  <strong>Comissaogerente:</strong>
  <%= @perm.comissaogerente %>
</p>

<p>
  <strong>Comissaocorretor:</strong>
  <%= @perm.comissaocorretor %>
</p>

<p>
  <strong>Idgerente:</strong>
  <%= @perm.idgerente %>
</p>

<p>
  <strong>User:</strong>
  <%= @perm.user_id %>
</p>

<%= link_to 'Edit', edit_perm_path(@perm) %> |
<%= link_to 'Back', perms_path %>